name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Assemble APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '1.8'
          distribution: temurin

      - name: Build APK
        run: chmod +x ./gradlew && ./gradlew assembleDebug

      - name: calligraph-apk
        uses: actions/upload-artifact@v4
        with:
          name: calligraph-apk
          path: app/build/outputs/apk/debug/app-debug.apk
